controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
  
    simple_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

simple_velocity_controller:
  ros__parameters:
    joints:
      - motor1_spinner1_joint
      - motor2_spinner2_joint
      - motor3_spinner3_joint
      - motor4_spinner4_joint